/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.AbstractCollection;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
//import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;



/**
 *
 * @author Admin
 */
public class companydetails extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form companydetails
     */
    public companydetails() {
        initComponents();
         conn=javaconnect.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_required = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_compid = new javax.swing.JTextField();
        txt_compname = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_phoneno = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_website = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(148, 41, 249));
        jPanel1.setLayout(null);
        jPanel1.add(txt_required);
        txt_required.setBounds(530, 470, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("New Company Details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 420, 340, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\private32.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 640, 410);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\private33.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(710, 10, 600, 410);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Category");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(720, 610, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Company_ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 470, 80, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CompanyName");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 520, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 580, 80, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Phone No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 650, 80, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 480, 80, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Website");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(420, 540, 80, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Salary");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(420, 590, 80, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Required");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(420, 640, 80, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Qualification");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(720, 490, 80, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Experience");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(720, 550, 80, 15);

        txt_compid.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txt_compidComponentMoved(evt);
            }
        });
        txt_compid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_compidKeyReleased(evt);
            }
        });
        jPanel1.add(txt_compid);
        txt_compid.setBounds(190, 460, 140, 30);

        txt_compname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_compnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_compname);
        txt_compname.setBounds(190, 520, 140, 30);
        jPanel1.add(txt_address);
        txt_address.setBounds(190, 580, 140, 30);

        txt_phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phonenoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_phoneno);
        txt_phoneno.setBounds(190, 640, 140, 30);
        jPanel1.add(txt_email);
        txt_email.setBounds(530, 640, 140, 30);
        jPanel1.add(txt_website);
        txt_website.setBounds(530, 590, 140, 30);
        jPanel1.add(txt_salary);
        txt_salary.setBounds(530, 530, 140, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Software", "Marketing", "Clerk", "Hardware", "Managerial", "Account" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(850, 610, 180, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B.E", "B.Sc", "B.CA", "B.BA", "B.Tech", "B.Com", "M.Com", "M.Sc" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(850, 480, 180, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(850, 540, 180, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(800, 670, 73, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(920, 670, 59, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_compnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_compnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_compnameActionPerformed

    private void txt_compidComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_compidComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_compidComponentMoved

    private void txt_phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phonenoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try{
            String sql="insert into company"
                    +"(companyid,companyname,address,phoneno,email,website,salary,required,qualifiaction,experience,catagory"
                    
                    +") values (?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_compid.getText());
            pst.setString(2,txt_compname.getText());
            pst.setString(3,txt_address.getText());
            pst.setString(4,txt_phoneno.getText());
            pst.setString(5,txt_email.getText());
            pst.setString(6,txt_website.getText());
             pst.setString(7,txt_salary.getText());
            pst.setString(8,txt_required.getText());
            pst.setString(9,(String) jComboBox1.getSelectedItem());
            pst.setString(10,(String) jComboBox2.getSelectedItem());
            pst.setString(11,(String) jComboBox3.getSelectedItem());
           
            

            
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");
            
                    
        }catch(Exception e)
        {
              JOptionPane.showMessageDialog(null,e);
            
        }
        finally{
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                  JOptionPane.showMessageDialog(null,e);
            
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        humanresource ob=new humanresource();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_compidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_compidKeyReleased
        // TODO add your handling code here:
         try{
            String sql="select * from company where companyid=?";
             pst=conn.prepareStatement(sql);
            pst.setString(1,txt_compid.getText());
           rs= pst.executeQuery();
           
           
           String add1=rs.getString("companyid");
           txt_compid.setText(add1);
           
           String add2=rs.getString("companyname");
           txt_compname.setText(add2);
           
           String add3=rs.getString("address");
           txt_address.setText(add3);
           
           String add4=rs.getString("phoneno");
           txt_phoneno.setText(add4);
           
           String add5=rs.getString("email");
           txt_email.setText(add5);
          
           String add6=rs.getString("website");
           txt_website.setText(add6);
           
            String add7=rs.getString("salary");
           txt_salary.setText(add7);
           
            String add8=rs.getString("required");
           txt_required.setText(add8);
          
          String add9=rs.getString("Qualifiaction");
          jComboBox1.setSelectedItem(add9);
          
          String add10=rs.getString("Experience");
          jComboBox2.setSelectedItem(add10);
          
          String add11=rs.getString("Catagory");
          jComboBox3.setSelectedItem(add11);
          
         
          
         
          
          
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally
        {
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_txt_compidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new companydetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_compid;
    private javax.swing.JTextField txt_compname;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_phoneno;
    private javax.swing.JTextField txt_required;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_website;
    // End of variables declaration//GEN-END:variables
}
