/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.AbstractCollection;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
//import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class company extends javax.swing.JFrame {
    Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form company
     */
    public company() {
        initComponents();
        conn=javaconnect.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_clear = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        txt_duration = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_modules = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_domain = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_client = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_proname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_proid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.setLayout(null);

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(710, 410, 100, 40);

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(420, 410, 110, 40);

        btn_insert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insert);
        btn_insert.setBounds(280, 410, 110, 40);
        jPanel1.add(txt_duration);
        txt_duration.setBounds(620, 330, 170, 30);

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(560, 410, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Duration");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 330, 110, 22);
        jPanel1.add(txt_modules);
        txt_modules.setBounds(620, 270, 170, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modules");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 270, 100, 22);
        jPanel1.add(txt_domain);
        txt_domain.setBounds(620, 210, 170, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Domain");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 210, 90, 22);
        jPanel1.add(txt_client);
        txt_client.setBounds(270, 320, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Client");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 320, 110, 22);
        jPanel1.add(txt_proname);
        txt_proname.setBounds(270, 260, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Project Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 260, 130, 20);
        jPanel1.add(txt_proid);
        txt_proid.setBounds(270, 200, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Project ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 150, 110, 22);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(340, 150, 280, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Project Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 100, 370, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Project ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 200, 110, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(730, 80, 83, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\private21.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 860, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        humanresource ob=new humanresource();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
        try{
            
            String value1=txt_proid.getText();
            String value2=txt_proname.getText();
            String value3=txt_client.getText();
            String value4=txt_domain.getText();
            String value5=txt_modules.getText();
            String value6=txt_duration.getText();
            
            
            String sql = "insert into project (id,projectname,clients,domain,modules,duration) values ('"+value1+"','"+value2+"','"+value3+"','"+value4+"','"+value5+"','"+value6+"') ";
        
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"project details inserted");
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e)
            {
                
            }
        }
        
    }//GEN-LAST:event_btn_insertActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
         try{
            String sql="select * from project where id=?";
             pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
           rs= pst.executeQuery();
           
           
           String add1=rs.getString("id");
           txt_proid.setText(add1);
           
           String add2=rs.getString("projectname");
           txt_proname.setText(add2);
           
           String add3=rs.getString("clients");
           txt_client.setText(add3);
           
           String add4=rs.getString("domain");
           txt_domain.setText(add4);
           
            String add14=rs.getString("modules");
           txt_modules.setText(add14);
          
          String add12=rs.getString("duration");
           txt_duration.setText(add12);
          
          
         
         
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally
        {
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_proid.setText("");
        txt_proname.setText("");
        txt_client.setText("");
        txt_domain.setText("");
        txt_modules.setText("");
        txt_duration.setText("");
       
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try{
            String sql="delete from project where id=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_proid.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Record Deleted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
        finally
        {
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
       
         
        try{
          String val=txt_proid.getText();
          String val2=txt_proname.getText();
          String val3=txt_client.getText();
          String val4=txt_domain.getText();
          String val5=txt_modules.getText();
          String val6=txt_duration.getText();
          
          
          String sql= "update project set id = '"+val+"',projectname = '"+val2+"',clients = '"+val3+"',"
           + "domain = '"+val4+"',modules = '"+val5+"',duration = '"+val6+"'   ";
          
          pst=conn.prepareStatement(sql);
          pst.execute();
          JOptionPane.showMessageDialog(null,"Record Updates");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
        
        finally{
            try{
                
            }
            catch(Exception e)
            {
                
            }
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_client;
    private javax.swing.JTextField txt_domain;
    private javax.swing.JTextField txt_duration;
    private javax.swing.JTextField txt_modules;
    private javax.swing.JTextField txt_proid;
    private javax.swing.JTextField txt_proname;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
