/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.AbstractCollection;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Admin
 */
public class employeeAllowance extends javax.swing.JFrame {
   Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
  //  private Object Emp;

    /**
     * Creates new form employeeAllowance
     */
    public employeeAllowance() {
        initComponents();
        conn=javaconnect.ConnecrDB();
            Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
      //  lbl_empid.setText(String.valueOf(Emp.empId).toString());
        Update_Table();
        
    }
    private void Update_Table()
    {
        try{
            String sql="select * from Allowance1";
             pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          table_allowance.setModel(DbUtils.resultSetToTableModel(rs));
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_empid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_department = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_allowance = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_overtime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_med = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_bonus = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_other = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_hw = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_rate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lbl_empid = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\private24.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 0, 1020, 240);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Employee ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 240, 140, 30);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(220, 240, 410, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Emp_id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 310, 100, 17);
        jPanel1.add(txt_empid);
        txt_empid.setBounds(160, 300, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("FirstName");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 350, 90, 17);
        jPanel1.add(txt_firstname);
        txt_firstname.setBounds(160, 340, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Surname:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 400, 80, 17);
        jPanel1.add(txt_surname);
        txt_surname.setBounds(160, 390, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("dob");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 440, 100, 17);
        jPanel1.add(txt_dob);
        txt_dob.setBounds(160, 430, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("BasicSalary");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 480, 100, 17);
        jPanel1.add(txt_salary);
        txt_salary.setBounds(160, 470, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Department");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 520, 100, 17);
        jPanel1.add(txt_department);
        txt_department.setBounds(160, 520, 220, 30);

        table_allowance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "overtime", "medical", "bonus", "other", "emp_id", "salary", "rate", "total_allowance", "firstname", "surname", "created_by"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_allowance);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 560, 690, 240);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("OverTime:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(390, 310, 100, 17);

        txt_overtime.setText("0");
        txt_overtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_overtimeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_overtime);
        txt_overtime.setBounds(480, 310, 190, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Medical:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(390, 360, 80, 17);

        txt_med.setText("0");
        jPanel1.add(txt_med);
        txt_med.setBounds(480, 360, 190, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Bonus:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(390, 410, 50, 17);

        txt_bonus.setText("0");
        jPanel1.add(txt_bonus);
        txt_bonus.setBounds(480, 410, 190, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Other:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(390, 460, 60, 17);

        txt_other.setText("0");
        txt_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otherActionPerformed(evt);
            }
        });
        jPanel1.add(txt_other);
        txt_other.setBounds(480, 460, 190, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Total Overtime:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(680, 320, 110, 17);

        txt_hw.setText("0");
        jPanel1.add(txt_hw);
        txt_hw.setBounds(790, 320, 170, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Rate Per Hour:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(680, 380, 120, 30);

        txt_rate.setText("0");
        txt_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_rate);
        txt_rate.setBounds(790, 380, 170, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Total Amount:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(550, 520, 150, 22);

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_total.setText("0.00");
        jPanel1.add(lbl_total);
        lbl_total.setBounds(720, 520, 60, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(730, 580, 90, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(730, 630, 90, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(730, 680, 90, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Logged In As:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(690, 260, 110, 15);

        lbl_empid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_empid.setText("emp");
        jPanel1.add(lbl_empid);
        lbl_empid.setBounds(820, 260, 26, 15);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Back");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(750, 480, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_overtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_overtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_overtimeActionPerformed

    private void txt_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otherActionPerformed

    private void txt_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rateActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
         try{
            String sql="select * from newemployee1 where Emp_id=?";
             pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
           rs= pst.executeQuery();
           
           
           String add1=rs.getString("Emp_id");
           txt_empid.setText(add1);
           
           String add2=rs.getString("FirstName");
           txt_firstname.setText(add2);
           
           String add3=rs.getString("Surname");
           txt_surname.setText(add3);
           
           String add4=rs.getString("dob");
           txt_dob.setText(add4);
           
            String add14=rs.getString("BasicSalary");
           txt_salary.setText(add14);
          
          String add12=rs.getString("Department");
           txt_department.setText(add12);
          
          
         
         
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally
        {
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        humanresource ob=new humanresource();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            
            String value1=txt_salary.getText();
            String value2=txt_bonus.getText();
            String value3=txt_med.getText();
            String value4=txt_other.getText();
            String value5=txt_rate.getText();
            String value6=txt_hw.getText();
            String value7=lbl_total.getText();
            String value8=txt_empid.getText();
            String value9=txt_firstname.getText();
            String value10=txt_surname.getText();
            String value11=txt_overtime.getText();
            
            String sql = "insert into Allowance1 (emp_id,overtime,medical,bonus,other,salary,rate,total_allowance,firstname,surname) values ('"+value8+"','"+value11+"','"+value3+"','"+value2+"','"+value4+"','"+value1+"','"+value5+"','"+value7+"','"+value9+"','"+value10+"') ";
        
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Allowance Added");
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
            try{
                pst.close();
                rs.close();
            }
            catch(Exception e)
            {
                
            }
        }
        Update_Table();
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int salary = Integer.parseInt(txt_salary.getText());
         int overtime = Integer.parseInt(txt_overtime.getText());
         
         double eight = 8;
         double days = 25;
         double dbop = 0;
         double overtimerate = 1.5;
         
         //calculate the total hours of over time
         double total_overtime = overtime * overtimerate;
         String x= String.valueOf(total_overtime);
         txt_hw.setText(x);
         
         //calculate overall overtime
         dbop = salary /days/eight;
         String s=String.valueOf(dbop);
         txt_rate.setText(s);
         
          int med = Integer.parseInt(txt_med.getText());
           int bonus = Integer.parseInt(txt_bonus.getText());
            int other = Integer.parseInt(txt_other.getText());
            int f = med+bonus+other;
            double calc = total_overtime * dbop + f;
            String c = String.valueOf(calc);
            lbl_total.setText(c);
            
            
            
            
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        txt_empid.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_dob.setText("");
        txt_salary.setText("");
         txt_department.setText("");
        txt_med.setText("0");
         txt_bonus.setText("0");
         txt_other.setText("0");
        txt_hw.setText("0");
         txt_rate.setText("0");
         txt_overtime.setText("0");
       lbl_total.setText("0.00");
       txt_search.setText("");
       
            
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeAllowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeAllowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeAllowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeAllowance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeAllowance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_empid;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable table_allowance;
    private javax.swing.JTextField txt_bonus;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_hw;
    private javax.swing.JTextField txt_med;
    private javax.swing.JTextField txt_other;
    private javax.swing.JTextField txt_overtime;
    private javax.swing.JTextField txt_rate;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables

   
}
