/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.AbstractCollection;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
//import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class Training extends javax.swing.JFrame {
   Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form Training
     */
    public Training() {
        initComponents();
        conn=javaconnect.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_mstatus = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_jnature = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_jcode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_ref = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txt_blood = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_eid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Thankyou");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1150, 230, 140, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(940, 493, 90, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(810, 490, 90, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(670, 490, 90, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(500, 490, 100, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 490, 65, 30);
        jPanel1.add(txt_address);
        txt_address.setBounds(950, 400, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("DateofBirth");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 310, 90, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Ref:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(850, 320, 28, 17);
        jPanel1.add(txt_mstatus);
        txt_mstatus.setBounds(950, 250, 160, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Paddress");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(840, 400, 90, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Mstatus:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(840, 250, 70, 17);
        jPanel1.add(txt_jnature);
        txt_jnature.setBounds(950, 180, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("JNature");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(840, 180, 80, 17);
        jPanel1.add(txt_jcode);
        txt_jcode.setBounds(570, 390, 180, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Jcode");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 390, 50, 17);
        jPanel1.add(txt_email);
        txt_email.setBounds(210, 300, 180, 30);

        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dob);
        txt_dob.setBounds(570, 310, 180, 30);
        jPanel1.add(txt_ref);
        txt_ref.setBounds(950, 310, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("BloodGroup:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 250, 90, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PExperience:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, 180, 100, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B.E", "B.Sc", "B.CA", "B.BA", "B.Tech", "B.Com", "M.Com", "M.Sc", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 380, 180, 30);

        txt_blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bloodActionPerformed(evt);
            }
        });
        jPanel1.add(txt_blood);
        txt_blood.setBounds(570, 240, 180, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(570, 180, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Qualification:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 380, 90, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 310, 50, 17);
        jPanel1.add(txt_ename);
        txt_ename.setBounds(210, 240, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ename:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 240, 60, 17);

        txt_eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_eidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_eid);
        txt_eid.setBounds(210, 170, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Eid:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 170, 40, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Employee No:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 90, 100, 17);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(310, 90, 260, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(900, 80, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\private20.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 70, 1250, 550);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 204));
        jLabel2.setText("Placement Training");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 20, 390, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        humanresource ob=new humanresource();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_eidActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txt_bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bloodActionPerformed

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String sql="insert into training"
                    +"(id,ename,email,qualification,"
                    +"pexperience,bloodgroup,dob,jcode,jnature,"
                    +"mstatus,ref,paddress) values (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_eid.getText());
            pst.setString(2,txt_ename.getText());
            pst.setString(3,txt_email.getText());
            pst.setString(4,(String) jComboBox1.getSelectedItem());
             pst.setString(5,(String) jComboBox2.getSelectedItem());
            pst.setString(6,txt_blood.getText());
            pst.setString(7,txt_dob.getText());
            pst.setString(8,txt_jcode.getText());
             pst.setString(9,txt_jnature.getText());
            pst.setString(10,txt_mstatus.getText());
            pst.setString(11,txt_ref.getText());
             pst.setString(12,txt_address.getText());
           
            

            
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");
            
                    
        }catch(Exception e)
        {
              JOptionPane.showMessageDialog(null,e);
            
        }
        finally{
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                  JOptionPane.showMessageDialog(null,e);
            
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        humanresource ob=new humanresource();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
          String val=txt_eid.getText();
          String val2=txt_ename.getText();
          String val3=txt_email.getText();
          String val4=(String) jComboBox1.getSelectedItem();
          String val5=(String) jComboBox2.getSelectedItem();
          String val6=txt_blood.getText();
          String val7=txt_dob.getText();
          String val8=txt_jcode.getText();
          String val9=txt_jnature.getText();
          String val10=txt_mstatus.getText();
          String val11=txt_ref.getText();
          String val12=txt_address.getText();
          
           String sql= "update training set id = '"+val+"',ename = '"+val2+"',email = '"+val3+"',"
           + "qualification = '"+val4+"',pexperience = '"+val5+"',bloodgroup = '"+val6+"',"
           + "dob = '"+val7+"',jcode = '"+val8+"', jnature = '"+ val9+"',mstatus = '"+val10+"',ref = '"+val11+"',paddress = '"+val12+"' where id = '"+val+"'   ";
          
          pst=conn.prepareStatement(sql);
          pst.execute();
          
          
         
          pst=conn.prepareStatement(sql);
          pst.execute();
          JOptionPane.showMessageDialog(null,"Record Updates");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
        
        finally{
            try{
                
            }
            catch(Exception e)
            {
                
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try{
            String sql="select * from training where id=?";
             pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
           rs= pst.executeQuery();
           
           
           String add1=rs.getString("id");
           txt_eid.setText(add1);
           
           String add2=rs.getString("ename");
           txt_ename.setText(add2);
           
           String add3=rs.getString("email");
           txt_email.setText(add3);
           
           String add4=rs.getString("qualification");
           jComboBox1.setSelectedItem(add4);
           
            String add5=rs.getString("pexperience");
             jComboBox2.setSelectedItem(add5);
          
          String add6=rs.getString("bloodgroup");
           txt_blood.setText(add6);
          
          String add7=rs.getString("dob");
           txt_dob.setText(add7);
         
         String add8=rs.getString("jcode");
           txt_jcode.setText(add8);
           
           String add9=rs.getString("jnature");
           txt_jnature.setText(add9);
           
           String add10=rs.getString("mstatus");
           txt_mstatus.setText(add10);
           
           String add11=rs.getString("ref");
           txt_ref.setText(add11);
           
           String add12=rs.getString("paddress");
           txt_address.setText(add12);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        finally
        {
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         txt_eid.setText("");
        txt_ename.setText("");
        txt_email.setText("");
        jComboBox1.setToolTipText("");
        jComboBox2.setToolTipText("");
        txt_blood.setText("");
        txt_dob.setText("");
        txt_jcode.setText("");
        txt_jnature.setText("");
        txt_mstatus.setText("");
        txt_ref.setText("");
        txt_address.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            String sql="delete from training where id=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_eid.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Record Deleted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            
        }
        finally
        {
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        thanking obj=new thanking();
        obj.show();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Training.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Training.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Training.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Training.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Training().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_blood;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_eid;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_ename;
    private javax.swing.JTextField txt_jcode;
    private javax.swing.JTextField txt_jnature;
    private javax.swing.JTextField txt_mstatus;
    private javax.swing.JTextField txt_ref;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
